In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
data=pd.read_csv('loan_data.csv')
data    

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001003    Male     Yes          1      Graduate            No   
1    LP001005    Male     Yes          0      Graduate           Yes   
2    LP001006    Male     Yes          0  Not Graduate            No   
3    LP001008    Male      No          0      Graduate            No   
4    LP001013    Male     Yes          0  Not Graduate            No   
..        ...     ...     ...        ...           ...           ...   
376  LP002953    Male     Yes         3+      Graduate            No   
377  LP002974    Male     Yes          0      Graduate            No   
378  LP002978  Female      No          0      Graduate            No   
379  LP002979    Male     Yes         3+      Graduate            No   
380  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583             1508.0       128.0             360.0   
1               3000                0.0        66.0             360.0   
2               2583             2358.0       120.0             360.0   
3               6000                0.0       141.0             360.0   
4               2333             1516.0        95.0             360.0   
..               ...                ...         ...               ...   
376             5703                0.0       128.0             360.0   
377             3232             1950.0       108.0             360.0   
378             2900                0.0        71.0             360.0   
379             4106                0.0        40.0             180.0   
380             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Rural           N  
1               1.0         Urban           Y  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
376             1.0         Urban           Y  
377             1.0         Rural           Y  
378             1.0         Rural           Y  
379             1.0         Rural           Y  
380             0.0     Semiurban           N  

[381 rows x 13 columns]

In [3]:
data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001003   Male     Yes          1      Graduate            No   
1  LP001005   Male     Yes          0      Graduate           Yes   
2  LP001006   Male     Yes          0  Not Graduate            No   
3  LP001008   Male      No          0      Graduate            No   
4  LP001013   Male     Yes          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583             1508.0       128.0             360.0   
1             3000                0.0        66.0             360.0   
2             2583             2358.0       120.0             360.0   
3             6000                0.0       141.0             360.0   
4             2333             1516.0        95.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Rural           N  
1             1.0         Urban           Y  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [5]:
data['Loan_Amount_Term'].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  84.,  12.,  36.])

In [6]:
data.drop('Loan_ID',axis=1,inplace=True)

In [7]:
data.isna().sum()


Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
data.fillna(method='ffill', inplace=True)

In [9]:
data.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [10]:
data.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       381.000000         381.000000  381.000000        381.000000   
mean       3579.845144        1277.275381  104.986877        341.102362   
std        1419.813818        2340.818114   28.358464         68.513253   
min         150.000000           0.000000    9.000000         12.000000   
25%        2600.000000           0.000000   90.000000        360.000000   
50%        3333.000000         983.000000  110.000000        360.000000   
75%        4288.000000        2016.000000  127.000000        360.000000   
max        9703.000000       33837.000000  150.000000        480.000000   

       Credit_History  
count      381.000000  
mean         0.839895  
std          0.367186  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [11]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [12]:
# data.loc['3+', 'Dependents'] = 3

In [13]:
data['Gender']=label_encoder.fit_transform(data['Gender'])
data['Married']=label_encoder.fit_transform(data['Married'])
data['Education']=label_encoder.fit_transform(data['Education'])
data['Property_Area']=label_encoder.fit_transform(data['Property_Area'])
data['Loan_Status']=label_encoder.fit_transform(data['Loan_Status'])
data['Self_Employed']=label_encoder.fit_transform(data['Self_Employed'])
data['Dependents']=label_encoder.fit_transform(data['Dependents'])

In [14]:
data

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        1           1          0              0             4583   
1         1        1           0          0              1             3000   
2         1        1           0          1              0             2583   
3         1        0           0          0              0             6000   
4         1        1           0          1              0             2333   
..      ...      ...         ...        ...            ...              ...   
376       1        1           3          0              0             5703   
377       1        1           0          0              0             3232   
378       0        0           0          0              0             2900   
379       1        1           3          0              0             4106   
380       0        0           0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0               1508.0       128.0             360.0             1.0   
1                  0.0        66.0             360.0             1.0   
2               2358.0       120.0             360.0             1.0   
3                  0.0       141.0             360.0             1.0   
4               1516.0        95.0             360.0             1.0   
..                 ...         ...               ...             ...   
376                0.0       128.0             360.0             1.0   
377             1950.0       108.0             360.0             1.0   
378                0.0        71.0             360.0             1.0   
379                0.0        40.0             180.0             1.0   
380                0.0       133.0             360.0             0.0   

     Property_Area  Loan_Status  
0                0            0  
1                2            1  
2                2            1  
3                2            1  
4                2            1  
..             ...          ...  
376              2            1  
377              0            1  
378              0            1  
379              0            1  
380              1            0  

[381 rows x 12 columns]

In [15]:
y=data['Loan_Status']
x=data.drop(['Loan_Status'],axis=1)

In [16]:
x

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        1           1          0              0             4583   
1         1        1           0          0              1             3000   
2         1        1           0          1              0             2583   
3         1        0           0          0              0             6000   
4         1        1           0          1              0             2333   
..      ...      ...         ...        ...            ...              ...   
376       1        1           3          0              0             5703   
377       1        1           0          0              0             3232   
378       0        0           0          0              0             2900   
379       1        1           3          0              0             4106   
380       0        0           0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0               1508.0       128.0             360.0             1.0   
1                  0.0        66.0             360.0             1.0   
2               2358.0       120.0             360.0             1.0   
3                  0.0       141.0             360.0             1.0   
4               1516.0        95.0             360.0             1.0   
..                 ...         ...               ...             ...   
376                0.0       128.0             360.0             1.0   
377             1950.0       108.0             360.0             1.0   
378                0.0        71.0             360.0             1.0   
379                0.0        40.0             180.0             1.0   
380                0.0       133.0             360.0             0.0   

     Property_Area  
0                0  
1                2  
2                2  
3                2  
4                2  
..             ...  
376              2  
377              0  
378              0  
379              0  
380              1  

[381 rows x 11 columns]

In [17]:
for i in data['Dependents']:
    print(i)

1
0
0
0
0
2
2
0
2
0
1
0
0
0
0
0
2
0
2
0
2
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
2
0
0
2
0
3
0
0
3
0
2
0
3
0
1
3
0
1
0
2
0
0
2
0
0
0
0
0
0
2
1
0
3
0
0
0
1
0
0
2
0
0
0
0
0
0
2
2
0
0
1
0
0
2
0
0
0
1
0
0
0
0
0
3
0
0
2
1
0
0
0
0
1
0
0
0
0
0
0
1
1
2
0
0
0
0
0
3
3
0
3
0
0
2
2
0
2
0
0
0
1
0
0
1
0
1
1
2
1
2
0
0
2
1
1
0
2
0
0
3
3
0
0
0
2
0
1
0
0
0
2
1
0
0
0
2
0
0
0
0
0
0
2
2
2
3
1
1
0
0
0
1
0
0
0
0
0
0
2
1
2
0
1
0
3
0
0
0
0
1
0
0
0
0
0
3
2
2
3
0
0
0
1
0
1
0
0
0
0
0
0
1
0
0
3
0
0
2
0
0
2
1
0
0
0
0
2
2
2
0
0
0
0
2
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
2
0
0
1
0
0
0
0
0
3
1
2
0
2
2
2
0
0
0
2
0
2
3
1
0
0
3
2
0
1
3
0
2
3
0
1
2
0
0
0
0
1
0
0
1
0
0
1
0
0
0
2
0
3
2
2
0
2
0
3
0
1
0
3
2
0
2
0
1
0
1
1
0
0
0
0
0
0
1
0
2
0
0
0
3
0
0
3
2
0
0
1
0
0
1
1
0
0
0
2
0
0
0
0
3
0
0
3
0


In [18]:
data['Dependents'].unique()

array([1, 0, 2, 3])

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
Rf=RandomForestClassifier()

In [22]:
x[44:45]
y[44:45]


44    1
Name: Loan_Status, dtype: int32

In [23]:
model=Rf.fit(x_train,y_train)
prediction=model.predict([[1,1,2,1,0,3357,2859.0,144.0,360.0,1.0,2]])
prediction

c:\Users\hisha\anaconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [24]:
model.score(x_test,y_test)

0.8608695652173913

In [25]:
model.score(x_train,y_train)

1.0

In [26]:
import pickle

In [27]:
V=open('Loan.pkl','wb')

In [28]:
V1=pickle.dump(model,V)
